### PR TITLE
Fix: remove user-facing tag feature and manual JSON editing instructions

### LINKED ISSUE #214: [PE-D][Tester B] Violation of "Constraint-Typing-Preferred"
In the tP: Constraints, it was stated that `The product should be targeting users who can type fast and prefer typing over other means of input.` 

The Tag feature **forces** user from CLI to file-editing mode. A user who types fast expects to achieve their goals through efficient commands (e.g., tag 1 t/VIP). Forcing them to close the app, navigate a file system, and manually ensure JSON syntax integrity (like adding commas and brackets) breaks the high-speed that is the product's primary value proposition. 

-------------
Labels: `severity.High` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by NotDotManish**
Fixes #214 

## Summary
Removes Tag as a user-facing feature to align with the product constraint that users should be able to perform tasks efficiently via CLI without requiring manual JSON editing.

## Changes
- Removed "Advanced: assigning tags manually" section from User Guide
- Removed FAQ entry instructing users to edit JSON for tags
- Removed tags from sample data to prevent user confusion
- Kept internal tag-related code to minimize LOC and avoid breaking existing functionality

## Rationale
The previous implementation required users to manually edit the JSON file to assign tags, which contradicts the product's goal of supporting fast CLI-based workflows.

## Testing
- `./gradlew checkstyleMain`
- `./gradlew test`
- `./gradlew clean build`

All checks pass.

### CODE REVIEW

File: src/main/java/seedu/address/model/util/SampleDataUtil.java [hunk 1]
```diff
@@ -24,35 +21,35 @@ public static Person[] getSamplePersons() {
                     new Name("Alex Yeoh"),
                     new Phone("87438807"),
                     new Email("alexyeoh@example.com"),
```
Comment (ephtale) [inline src/main/java/seedu/address/model/util/SampleDataUtil.java:23]: Remember to update any existing screenshot that still shows this feature (IMPORTANT), else we risk confusion in UG

**Review by ephtale — APPROVED** [review]
Looks good
