### PR TITLE
Fix set-validity filter reset

### LINKED ISSUE #147: set-validity resets active filters
Running `set-validity` resets active filters unexpectedly.

**Steps to Reproduce**  
1. Apply a client filter so only a subset of clients is visible  
2. Run `set-validity` on one of the visible clients

**Expected Behaviour**  
The command should update the client’s validity while keeping the current filters intact.

**Actual Behaviour**  
The command resets filters because it calls `updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)`.

**Why This Is a Problem**  
`set-validity` is a data update command and should not unexpectedly change the user’s current filtered view.

### PR DESCRIPTION
**Pull request by NotDotManish**
Fixes #147 

### Summary
Prevent `set-validity` from resetting active filters.

### Details
- Removed the broad `updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)` call
- Kept filter state unchanged after updating a client's validity
- Added a test to verify the client filter remains in place

### Result
Running `set-validity` no longer clears active filters or resets the visible client list.

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/SetValidityCommandTest.java [hunk 1]
```diff
@@ -57,6 +60,32 @@ public void execute_validClientIndex_success() {
...
+        // Apply a filter so only Alice is visible
+        model.updateFilteredClientList(new NameContainsKeywordsPredicate(List.of("Alice")));
+        assertEquals(1, model.getFilteredClientList().size());
+
+        // Run set-validity on the first (and only) visible client
+        new SetValidityCommand(INDEX_FIRST_PERSON, new Validity("2026-12-31")).execute(model);
+
+        // Filter must still be in place — list should still show only 1 client
+        assertEquals(1, model.getFilteredClientList().size());
+        assertEquals("Alice", model.getFilteredClientList().get(0).getName().getFullName());
```
Comment (prithvibhardwaj) [inline src/test/java/seedu/address/logic/commands/SetValidityCommandTest.java]: The tests are comprehensive
