### PR TITLE
Fix: enforce digits-only phone numbers to prevent duplicate bypass vi…

### LINKED ISSUE #184: [PE-D][Tester A] Phone numbers with different formatting bypass duplicate detection
Two entries with the same logical phone number but different formatting (e.g., with and without spaces) are treated as different people, bypassing duplicate detection entirely.

Steps to reproduce:

Launch the app with java -jar GymOps.jar
Run: list
Run: add-trainer n/TestA p/91234567 e/a@test.com
Run: 

Expected: The app should detect that 91234567 and 9123 4567 are the same phone number and reject the duplicate, or at least warn the user.

Actual: Both trainers are added successfully as separate entries. The app performs exact string matching on phone numbers with no normalization (stripping spaces, dashes, or + prefix), so the same real-world number stored with different formatting creates duplicate entries.

Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by NotDotManish**
Fixes #184 

## Summary
Prevents duplicate detection bypass caused by differently formatted phone numbers (e.g. `91234567` vs `9123 4567`) by enforcing digits-only phone input.

## Changes
- Restricted phone number validation to digits only
- Updated validation message to reflect new constraint
- Updated test to reject phone numbers with spaces

## Rationale
Previously, the app accepted phone numbers with spaces or symbols, causing logically identical numbers to be treated as different values. This allowed duplicate entries to bypass detection. Enforcing digits-only input ensures consistent representation.

## Testing
- `./gradlew checkstyleMain`
- `./gradlew test`
- `./gradlew clean build`

All checks pass.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -10,9 +10,8 @@
 public class Phone {
 
     public static final String MESSAGE_CONSTRAINTS =
-        "Phone numbers can contain numbers, spaces, '+', '-', '(', ')', must have at least 3 digits, "
-        + "and be no more than 20 characters in total.";
-    public static final String VALIDATION_REGEX = "[\\d\\s\\+\\-\\(\\)]+";
+        "Phone numbers must contain digits only, with at least 3 and no more than 20 digits.";
+    public static final String VALIDATION_REGEX = "\\d+";
```
Comment (ephtale) [inline src/main/java/seedu/address/model/person/Phone.java:14]: Seems right, will check again later

**Review by ephtale — APPROVED** [review]
Will merge for now
