### PR TITLE
Fix: reject unknown prefixes in add-trainer parsing

### LINKED ISSUE #232: [PE-D][Tester C] add-trainer rejects command when there are extra parameters
Steps to reproduce:
Run: `add-trainer n/John p/911 e/j@ee.com x/extra`

Expected: The command succeeds.

Actual: `Emails should be of the format local-part@domain...` implies email is invalid.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by NotDotManish**
Fixes #232 

## Summary
Rejects unknown prefixes in `add-trainer` parsing so invalid parameters such as `x/extra` do not get absorbed into valid fields like email.

## Changes
- Added detection for unknown prefixes before tokenization
- Updated `AddTrainerCommandParser` to reject unknown prefixes cleanly
- Added parser test for unknown prefix input

## Rationale
Previously, unknown prefixes such as `x/` were not recognised and could be absorbed into the preceding field value, causing misleading validation failures. This fix ensures invalid prefixes are rejected directly.

## Testing
- `./gradlew checkstyleMain`
- `./gradlew test`
- `./gradlew clean build`

All checks pass.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java [hunk 1]
```diff
@@ -28,6 +29,31 @@ public static ArgumentMultimap tokenize(String argsString, Prefix... prefixes) {
...
+    /**
+     * Returns true if {@code argsString} contains any prefix-like token (of the form {@code [a-zA-Z]+/})
+     * that is not among the given {@code knownPrefixes}. Used to detect unknown prefixes before they
+     * are silently absorbed into an adjacent field's value.
+     *
+     * @param argsString   Arguments string to inspect
+     * @param knownPrefixes Prefixes that are valid for the current command
+     * @return             True if an unrecognised prefix-like token is present
+     */
+    public static boolean hasUnknownPrefix(String argsString, Prefix... knownPrefixes) {
```
Comment (ephtale) [inline src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java:41]: If it passes the tests then it probably won't break existing parsing so I'll approve this

**Review by ephtale — APPROVED** [review]
Look good
